# author Junji Takakura <j.takakura@gmail.com>

name: spine_core
description: The spine-core runtime provides functionality to load and manipulate Spine skeletal animation data using Dart.
version: 0.3.3
homepage: null
publish_to: "none"


environment:
  sdk: ">=2.17.3 <3.0.0"

